---
# handlers file for postfix

- name: "reconfigure"
  command: dpkg-reconfigure --frontend=noninteractive postfix
  notify: restart postfix

- name: "restart postfix"
  service:
    name: 'postfix'
    state: 'restarted'
  notify: send test email
  when:
    - "'postfix' in ansible_facts.packages"

- name: "send test email"
  mail:
    host: 'localhost'
    port: 25
    from: "root@{{ postfix_domain }}"
    to: "root@{{ postfix_domain }}"
    subject: '{{ ansible_hostname }} can send emails'
    body: 'If you receive this, SMTP is configured by Ansible role "{{ role_name }}" on {{ ansible_hostname }}.'
  when: postfix_main_mailer_type is defined and postfix_main_mailer_type != "No configuration"

- name: "run newaliases"
  command: newaliases

- name: "rebuild access table"
  command: postmap /etc/postfix/access

- name: "rebuild transport table"
  command: postmap /etc/postfix/transport
